[providers]
node = "20"

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build:min"]

[start]
cmd = "node dist/minimal-server.js"

